# Generated by Django 3.2.18 on 2023-03-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0002_alter_task_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='user',
        ),
    ]
